import Head from "next/head";
import Link from "next/link";
import fs from "fs";
import path from "path";

export async function getStaticProps() {
  
  const data = fs.readFileSync(path.join(process.cwd(), "/public/db.json"));

  const appData = JSON.parse(data);

  let newArray = Object.entries(appData[0]).map(
    ([key, value]) => value
  );

  return {
    props: {
      newArray
    },
  };
}

export default function Home({newArray}) {
  return (
    <>
      <Head>
        <title>Accueil | Ab Distribution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
          {newArray.map((item) => (
            <li key={item.id}>
              <Link href={`/products/${item.id}`}>
                <h1>{item.name}</h1>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
