"use client";
import Head from "next/head";

export default function Page() {
  return (
    <>
      <Head>
        <title>Accueil | AB Distribution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div
          className="landing"
          style={{
            "--color-primary": "#F35029",
            "--color-secondary": "#FAF7EE",
          }}
        >
          <div className="landing_inner">
            <h3>Explorez notre catalogue comprenant</h3>
            <h1>
              Une variété de produits <span>exceptionnels.</span>
            </h1>
          </div>
        </div>
      </section>
    </>
  );
}
